In [1]:
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
%matplotlib inline

In [2]:
heart_df = heart_df=pd.read_csv("C:\\Users\\Ankita & Subhash\\Desktop\\MSITM\\Fall Semester 2018\\Machine Learning\\Project\\Data From Competition Website\\train_values.csv")
heart_df.head()

patient_id  slope_of_peak_exercise_st_segment               thal  \
0     0z64un                                  1             normal   
1     ryoo3j                                  2             normal   
2     yt1s1x                                  1             normal   
3     l2xjde                                  1  reversible_defect   
4     oyt4ek                                  3  reversible_defect   

   resting_blood_pressure  chest_pain_type  num_major_vessels  \
0                     128                2                  0   
1                     110                3                  0   
2                     125                4                  3   
3                     152                4                  0   
4                     178                1                  0   

   fasting_blood_sugar_gt_120_mg_per_dl  resting_ekg_results  \
0                                     0                    2   
1                                     0                    0   
2                                     0                    2   
3                                     0                    0   
4                                     0                    2   

   serum_cholesterol_mg_per_dl  oldpeak_eq_st_depression  sex  age  \
0                          308                       0.0    1   45   
1                          214                       1.6    0   54   
2                          304                       0.0    1   77   
3                          223                       0.0    1   40   
4                          270                       4.2    1   59   

   max_heart_rate_achieved  exercise_induced_angina  heart_disease_present  
0                      170                        0                      0  
1                      158                        0                      0  
2                      162                        1                      1  
3                      181                        0                      1  
4                      145                        0                      0

In [3]:
heart_df.shape

(180, 15)

This above line of executed code indicates that there are 180 rows and 15 columns within the above dataset. In the next step let's divide the data into attributes and labels. 

## Data Preparation

In [4]:
heart_df.drop(['patient_id', 'thal'], axis=1, inplace=True)
heart_df.head()

X = heart_df.drop('heart_disease_present', axis=1)  
y = heart_df['heart_disease_present'] 

In the above code lines, X contains the attributes of the data frame and y contains the labels that we are willing to predict. 

In [5]:
# Data Splitting
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)  

## 1. Simple SVM

In [6]:
# Training the Algorithm
from sklearn.svm import SVC  
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
svclassifier = SVC(kernel='linear', degree=8)  
svclassifier.fit(X_train, y_train) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=8, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [59]:
# Making Predictions
y_pred = svclassifier.predict(X_test)

In [60]:
#Algorithm Evaluation
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  

[[20  3]
 [ 1 12]]
              precision    recall  f1-score   support

           0       0.95      0.87      0.91        23
           1       0.80      0.92      0.86        13

   micro avg       0.89      0.89      0.89        36
   macro avg       0.88      0.90      0.88        36
weighted avg       0.90      0.89      0.89        36



As compared to our previous Logistic Regression, this time using linear kernel helped in improving the model's performance to a high value.

### Hyperparameter Tuning

In [12]:
# Set the parameters by cross-validation
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from __future__ import print_function
print(__doc__)

tuned_parameters = [{'kernel': ['rbf'], 'gamma': [1e-3, 1e-4],
                     'C': [1, 10, 100, 1000]},
                    {'kernel': ['linear'], 'C': [1, 10, 100, 1000]}]

scores = ['precision', 'recall']

for score in scores:
    print("# Tuning hyper-parameters for %s" % score)
    print()

    clf = GridSearchCV(SVC(), tuned_parameters, cv=5,   #5 fold cross-validation
                       scoring='%s_macro' % score)
    clf.fit(X_train, y_train)

    print("Best parameters set found on development set:")
    print()
    print(clf.best_params_)
    print()
    print("Grid scores on development set:")
    print()
    means = clf.cv_results_['mean_test_score']
    stds = clf.cv_results_['std_test_score']
    for mean, std, params in zip(means, stds, clf.cv_results_['params']):
        print("%0.3f (+/-%0.03f) for %r"
              % (mean, std * 2, params))
    print()

    print("Detailed classification report:")
    print()
    print("The model is trained on the full development set.")
    print("The scores are computed on the full evaluation set.")
    print()
    y_true, y_pred = y_test, clf.predict(X_test)
    print(classification_report(y_true, y_pred))
    print()

Automatically created module for IPython interactive environment
# Tuning hyper-parameters for precision



C:\Users\Ankita & Subhash\AppData\Local\conda\conda\envs\analysis\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Best parameters set found on development set:

{'C': 1, 'kernel': 'linear'}

Grid scores on development set:

0.655 (+/-0.125) for {'C': 1, 'gamma': 0.001, 'kernel': 'rbf'}
0.611 (+/-0.072) for {'C': 1, 'gamma': 0.0001, 'kernel': 'rbf'}
0.551 (+/-0.114) for {'C': 10, 'gamma': 0.001, 'kernel': 'rbf'}
0.665 (+/-0.086) for {'C': 10, 'gamma': 0.0001, 'kernel': 'rbf'}
0.574 (+/-0.111) for {'C': 100, 'gamma': 0.001, 'kernel': 'rbf'}
0.699 (+/-0.139) for {'C': 100, 'gamma': 0.0001, 'kernel': 'rbf'}
0.603 (+/-0.094) for {'C': 1000, 'gamma': 0.001, 'kernel': 'rbf'}
0.731 (+/-0.069) for {'C': 1000, 'gamma': 0.0001, 'kernel': 'rbf'}
0.803 (+/-0.053) for {'C': 1, 'kernel': 'linear'}
0.777 (+/-0.101) for {'C': 10, 'kernel': 'linear'}
0.779 (+/-0.116) for {'C': 100, 'kernel': 'linear'}
0.743 (+/-0.161) for {'C': 1000, 'kernel': 'linear'}

Detailed classification report:

The model is trained on the full development set.
The scores are computed on the full evaluation set.

              precision    

C:\Users\Ankita & Subhash\AppData\Local\conda\conda\envs\analysis\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Best parameters set found on development set:

{'C': 1, 'kernel': 'linear'}

Grid scores on development set:

0.640 (+/-0.114) for {'C': 1, 'gamma': 0.001, 'kernel': 'rbf'}
0.588 (+/-0.058) for {'C': 1, 'gamma': 0.0001, 'kernel': 'rbf'}
0.551 (+/-0.115) for {'C': 10, 'gamma': 0.001, 'kernel': 'rbf'}
0.642 (+/-0.081) for {'C': 10, 'gamma': 0.0001, 'kernel': 'rbf'}
0.575 (+/-0.110) for {'C': 100, 'gamma': 0.001, 'kernel': 'rbf'}
0.687 (+/-0.143) for {'C': 100, 'gamma': 0.0001, 'kernel': 'rbf'}
0.604 (+/-0.096) for {'C': 1000, 'gamma': 0.001, 'kernel': 'rbf'}
0.721 (+/-0.076) for {'C': 1000, 'gamma': 0.0001, 'kernel': 'rbf'}
0.782 (+/-0.042) for {'C': 1, 'kernel': 'linear'}
0.746 (+/-0.082) for {'C': 10, 'kernel': 'linear'}
0.762 (+/-0.082) for {'C': 100, 'kernel': 'linear'}
0.733 (+/-0.154) for {'C': 1000, 'kernel': 'linear'}

Detailed classification report:

The model is trained on the full development set.
The scores are computed on the full evaluation set.

              precision    

## 2. Polynomial Kernel SVM

In [72]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='poly', degree=8)  
svclassifier.fit(X_train, y_train)  

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=8, gamma='auto_deprecated',
  kernel='poly', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [73]:
# Making Predictions
y_pred = svclassifier.predict(X_test)  

In [74]:
# Algorithm Evaluation
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))  

[[13 10]
 [ 2 11]]
              precision    recall  f1-score   support

           0       0.87      0.57      0.68        23
           1       0.52      0.85      0.65        13

   micro avg       0.67      0.67      0.67        36
   macro avg       0.70      0.71      0.67        36
weighted avg       0.74      0.67      0.67        36



This time our Model's performance seems to have detoriated than the previous Model.

## 3. Gaussian Kernel

In [75]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='rbf')  
svclassifier.fit(X_train, y_train) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [76]:
# Prediction and Evaluation
y_pred = svclassifier.predict(X_test)  

In [94]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8333333333333334


In [80]:
# Algorithm Evaluation
from sklearn.metrics import classification_report, confusion_matrix 
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))  

[[23  0]
 [13  0]]
              precision    recall  f1-score   support

           0       0.64      1.00      0.78        23
           1       0.00      0.00      0.00        13

   micro avg       0.64      0.64      0.64        36
   macro avg       0.32      0.50      0.39        36
weighted avg       0.41      0.64      0.50        36



C:\Users\Ankita & Subhash\AppData\Local\conda\conda\envs\analysis\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Okay this time, the Model's performance seemed to have detoriated much more than the previous Model. So, far Simple SVM seems to perform the best.

## 4. Sigmoid Kernel

In [81]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='sigmoid')  
svclassifier.fit(X_train, y_train) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='sigmoid', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [82]:
# Prediction and Evaluation
y_pred = svclassifier.predict(X_test) 

In [93]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8333333333333334


In [84]:
# Algorithm Evaluation
from sklearn.metrics import classification_report, confusion_matrix  
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))  

[[23  0]
 [13  0]]
              precision    recall  f1-score   support

           0       0.64      1.00      0.78        23
           1       0.00      0.00      0.00        13

   micro avg       0.64      0.64      0.64        36
   macro avg       0.32      0.50      0.39        36
weighted avg       0.41      0.64      0.50        36



C:\Users\Ankita & Subhash\AppData\Local\conda\conda\envs\analysis\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


So, running all the Models, our Simple SVM Model still semms to ein over all other SVM Models and it even performs better than our previous Models ran on the basis of Logistic Regression.

## 5. Decision Tree

In [86]:
from sklearn.tree import DecisionTreeClassifier  
classifier = DecisionTreeClassifier()  
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [87]:
# Prediction and Evaluation
y_pred = classifier.predict(X_test)  

In [92]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8333333333333334


In [88]:
# Algorithm Evaluation
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))  

[[17  6]
 [ 4  9]]
              precision    recall  f1-score   support

           0       0.81      0.74      0.77        23
           1       0.60      0.69      0.64        13

   micro avg       0.72      0.72      0.72        36
   macro avg       0.70      0.72      0.71        36
weighted avg       0.73      0.72      0.73        36



This Model performed however better than the previous Models, except for Simple SVM Model.

## 6. Random Forest

In [89]:
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

In [90]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8333333333333334


In [91]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred)) 

[[19  4]
 [ 2 11]]
              precision    recall  f1-score   support

           0       0.90      0.83      0.86        23
           1       0.73      0.85      0.79        13

   micro avg       0.83      0.83      0.83        36
   macro avg       0.82      0.84      0.82        36
weighted avg       0.84      0.83      0.84        36



In this Model, the Model Accuracy and Model F1 Score seems to be close and therefore we can conclude a better performance in terms of Model's predictive power.